sudo: false
language: go
git:
    depth: 1
install: go get -v github.com/gohugoio/hugo

script:
    - hugo --theme=hugo-theme-air
    - echo 'Hugo build done!'

after_script:
  - cd ./public
  - git init
  - git config user.name "Jenly"
  - git config user.email "jenly1314@gmail.com"
  - git add .
  - git commit -a -m "Auto update docs by Travis CI."
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master

branches:
  only:
    - hugo

env:
 global:
   - GH_REF: github.com/asvip/asvip.github.io.git