BaseUrl= "https://mbahack2.syui.cf/hugo-theme-air/"
LanguageCode= "en-US"
Title= "Hugo Theme Air"
paginate = 5
DisqusShortname = ""
Copyright = "All rights reserved - 2016"
canonifyurls = true

[author]
  name = "Jenly"

[params]
  description = ""
  cover = "images/logo.png"
  author = "Jenly"
  authorlocation = ""
  authorwebsite = "https://jenly1314.github.io"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  githubName = "jenly1314"
  twitterName = "jenly1314"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
